name: inception

services:
  nginx:
    build: 
      context: ./requirements/nginx/
      args:
        HOST_42: ${HOST_42:-kmehour.42.fr}
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/logs/:/var/log/nginx/
      - /home/kmehour/data/wordpress/:/www/wordpress/
    ports:
      - 443:443
    networks:
      frontend:
    environment:
      HOST_42: ${HOST_42:-kmehour.42.fr}
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress/
    depends_on:
      - database
    expose:
      - 9000 
    environment:
      WP_SUPER_USER: ${WP_SUPER_USER}
      WP_SUPER_PASSWORD: ${WP_SUPER_PASSWORD}
      WP_SUPER_EMAIL: ${WP_SUPER_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOST_42: ${HOST_42:-kmehour.42.fr}
    volumes:
      - /home/kmehour/data/wordpress/:/www/wordpress/
    networks:
      frontend:
      backend:
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb/
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER} 
      DB_HOST: mariadb
    volumes:
      - /home/kmehour/data/db/:/var/lib/mysql
    expose:
      - 3306
    networks:
      backend:
    restart: unless-stopped


networks:
  frontend:
    ipam:
      driver: default
  backend:
    ipam:
      driver: default

volumes:
  web_data:
  db_data:

secrets:
  my_secret:
    file: ../secrets/credentials.txt
