name: inception

services:
  nginx:
    build: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/logs/:/var/log/nginx/
      - ./requirements/nginx/tools/ssl/:/etc/nginx/ssl/:ro
      - web_data:/www/
    ports:
      - 443:443
    networks:
      frontend:
    environment:
      HOST_42: ${HOST_42}
    restart: always

  test_sql:
    image: mariadb:11.1
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - test_db_data:/var/lib/mysql 
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      backend:

  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - test_sql
    expose:
      - 9000 
    environment:
      WP_SUPER_USER: ${WP_SUPER_USER}
      WP_SUPER_PASSWORD: ${WP_SUPER_PASSWORD}
      WP_SUPER_EMAIL: ${WP_SUPER_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOST_42: ${HOST_42}
    volumes:
      - web_data:/www/
      # - ./requirements/wordpress/config/wp-config.php:/www/wordpress/wp-config.php:ro
    networks:
      frontend:
      backend:

  # db:
  #   build: ./requirements/mariadb/
  #   environment:
  #     DB_NAME: wordpress
  #     DB_PASSWORD: "rootroot"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   networks:
  #     backend:


networks:
  frontend:
    ipam:
      driver: default
  backend:
    ipam:
      driver: default

volumes:
  web_data:
  db_data:
  test_db_data:

secrets:
  my_secret:
    file: ../secrets/credentials.txt
