services:
  nginx:
    build: ./nginx/
    volumes:
      - ./nginx/inception.conf:/etc/nginx/http.d/default.conf:ro
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/www/:/www/
    ports:
     - 80:80
