services:
  nginx:
    build: ./nginx/
    volumes:
      - ./nginx/inception.conf:/etc/nginx/http.d/default.conf:ro
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/tools/www/:/www/
      - ./nginx/tools/ssl/:/etc/nginx/ssl/:ro
    ports:
      - 443:443
