name: inception

services:
  nginx:
    build: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/inception.conf:/etc/nginx/http.d/default.conf:ro
      - ./requirements/nginx/logs/:/var/log/nginx/
      - ./requirements/nginx/tools/www/:/www/
      - ./requirements/nginx/tools/ssl/:/etc/nginx/ssl/:ro
    ports:
      - 443:443

    networks:
      frontend:

  wordpress:
    build: ./requirements/wordpress
    # depends_on:
      # - db
    expose:
      - 9000 
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "rootroot"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./requirements/nginx/tools/www/:/www/
      # adduser -D -H -G wordpress_user wordpressuser

    networks:
      frontend:
      # backend:

  # db:
  #   image: "mysql:5.7"
  #   environment:
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_ROOT_PASSWORD: "rootroot"
  #   volumes:
  #     - ./volumes/mysql:/var/lib/mysql
  #   networks:
  #     backend:

networks:
  frontend:
    ipam:
      driver: default
  # backend:
  #   ipam:
  #     driver: default

secrets:
  my_secret:
    file: ../secrets/credentials.txt
